### ISSUE TITLE
undefined method `blank?' for an instance of String

### ISSUE THREAD

**Issue by maddox** [halorrr/lunchmoney-ruby#120]
Has this library been tested outside of Rails? It doesn't seem to work as it's attempting to use `.blank?`, which is typically included via ActiveSupport, but I don't see that included in the deps for this library.

Using this library on it's own won't work.

**Comment by maddox** [comment]
Honestly, even after manually requiring `active_support`, the library still won't run without failure

    lunchmoney/categories/category.rb:41:in `initialize': missing keyword: :children (ArgumentError)

My script is as simple as this:

```ruby
require 'rubygems'
require 'active_support'
require "active_support/core_ext/object/blank.rb"
require "active_support/core_ext/module/delegation.rb"
require 'lunchmoney-ruby'

api = LunchMoney::Api.new(api_key: "xxx")
api.all_categories
```

**Comment by halorrr** [comment]
Hey! The gem is still very much a work in progress, I took passes at most of the calls but am now working at going through them one by one, cleaning things up, and adding testing to make sure everything works. That being said let me answer the two issues here.

For the first one I see the issue, while activesupport is a required dependency for the gem:
https://github.com/halorrr/lunchmoney-ruby/blob/d295e178d27669eb459b8e76f04e55be4e9da515/lunchmoney-ruby.gemspec#L31

Looks like requiring the `blank` module is on main:
https://github.com/halorrr/lunchmoney-ruby/blob/4508b7ff9bdb19aa4305eef981ea4d65a1421cbd/lib/lunchmoney.rb#L6

but not on the latest version I have published:
https://github.com/halorrr/lunchmoney-ruby/blob/d295e178d27669eb459b8e76f04e55be4e9da515/lib/lunchmoney.rb#L4-L7

As for the second issue you noticed, that is because in October the categories object got some tweaks to it's fields and I didn't update the gem to support this yet:
https://lunchmoney.dev/#changelog

All that being said I'm trying to dedicate more time to the development here as I really want to use this for some of my own ideas I have (I literally just wrote myself up issues to get myself more organized yesterday https://github.com/users/halorrr/projects/1). 

Let me throw a fix together for the categories object and the missing require and get a new version published. (And if you are wondering, yes I plan in the future to make my objects not break completely when new fields are added to them)

**Comment by halorrr** [comment]
I've pushed a new release, update your gem version to 0.5.1 and those issues should be resolved.
